# Environment - is it production, test or local development?
env: test

treafik_host_routing: pywb.webarchiv.cz

# Directory where pywb is installed
# pywb_dir: /home/ansible/pywb

# Who owns directories & files
# owner: ansible
# group: ansible

# Directory where pywb is installed
pywb_dir: /home/pywb-prod

# Who owns directories & files
owner: pywb-prod
group: pywb-prod
