---
- name: "Prepare configuration template"
  hosts: all
  tasks:
    - name: User running pywb
      ansible.builtin.user:
        become: "{{ sudo | default(true) }}"
        name: "{{ owner }}"
        comment: Web archive replay system
        create_home: yes

    - name: "Prepare pywb operation directory"
      become: "{{ sudo | default(true) }}"
      file:
        owner: "{{ owner | default(omit) }}"
        group: "{{ group | default(omit) }}"
        dest: "{{ pywb_dir }}"
        state: directory

    - name: Install python
      ansible.builtin.pip:
        become: "{{ owner | default(omit) }}"
        name: pywb
        virtualenv: "{{ pywb_dir }}/venv"

    # - name: "Prepare configuration for static web."
    #   copy:
    #     dest: /home/ansible/seeder/static-nginx.conf
    #     content: |
    #       server {
    #         location /static/ {
    #             root /seeder;
    #         }
    #         location /media/ {
    #             root /seeder;
    #         }

    #         # Increase max upload size to ~50MB
    #         client_max_body_size 53M;

    #         listen 0.0.0.0:80;
    #       }

    # - name: "Deploy Docker Compose"
    #   template:
    #     src: "{{ item.src }}"
    #     dest: "{{ pywb_dir }}/{{ item.dest }}"
    #   loop:
    #     - src: docker-compose.yaml.j2
    #       dest: docker-compose-{{ env }}.yaml
    #     - src: config.yaml
    #       dest: config.yaml

    # - name: "Deployment scripts"
    #   template:
    #     src: "{{ item.src }}"
    #     dest: "{{ item.dest }}"
    #     mode: u+x
    #   loop:
    #     - src: run.sh
    #       dest: "{{ pywb_dir }}/run-{{ env }}.sh"
    #     - src: stop.sh
    #       dest: "{{ pywb_dir }}/stop-{{ env }}.sh"
    #     - src: logs.sh
    #       dest: "{{ pywb_dir }}/logs-{{ env }}.sh"
    #     - src: exec.sh
    #       dest: "{{ pywb_dir }}/exec-{{ env }}.sh"
    #     - src: docker.sh
    #       dest: "{{ pywb_dir }}/docker-{{ env }}.sh"
    #     - src: wb-manager.sh
    #       dest: "{{ pywb_dir }}/wb-manager-{{ env }}.sh"
