---
- name: PyWb Deployment
  hosts: all
  tasks:
    - name: Ensure service users
      become: "{{ sudo | default(true) }}"
      block:
        - name: User for running traefik service with sudo capability
          ansible.builtin.user:
            name: traefik
            comment: User for running traefik service with sudo capability
            create_home: yes
            shell: /bin/bash
            groups: sudo
            append: true
        - name: User for running pywb process with sudo capability
          ansible.builtin.user:
            name: "{{ owner }}"
            comment: User for running pywb process with sudo capability
            create_home: yes
            shell: /bin/bash
            groups: sudo
            append: true

    - name: Deploy Traefik as Reverse Proxy
      when: pywb_deployment == 'docker'
      become: "{{ sudo | default(true) }}"
      become_user: traefik
      block:
        - name: "Deploy Traefik compose"
          copy:
            src: "{{ item.src }}"
            dest: "/home/traefik/{{ item.dest }}"
          loop:
            - src: traefik/docker-compose.yaml
              dest: docker-compose.yaml
        - name: "Deploy Traefik wrappeers"
          copy:
            src: "{{ item.src }}"
            dest: "/home/traefik/{{ item.dest }}"
            mode: u+x
          loop:
            - src: traefik/run.sh
              dest: run.sh
            - src: traefik/stop.sh
              dest: stop.sh

    - name: Run pywb as Docker Image
      when: pywb_deployment == 'docker'
      become: "{{ sudo | default(true) }}"
      become_user: "{{ owner | default(omit) }}"
      block:
        - name: "Deploy Docker Compose"
          template:
            src: "{{ item.src }}"
            dest: "{{ pywb_dir }}/{{ item.dest }}"
          loop:
            - src: docker-compose.yaml.j2
              dest: docker-compose.yaml
            - src: config.yaml
              dest: config.yaml
        - name: "Deployment scripts"
          template:
            src: "{{ item.src }}"
            dest: "{{ item.dest }}"
            mode: u+x
          loop:
            - src: run.sh
              dest: "{{ pywb_dir }}/run.sh"
            - src: stop.sh
              dest: "{{ pywb_dir }}/stop.sh"
            - src: logs.sh
              dest: "{{ pywb_dir }}/logs.sh"
            - src: exec.sh
              dest: "{{ pywb_dir }}/exec.sh"
            - src: docker.sh
              dest: "{{ pywb_dir }}/docker.sh"
            - src: wb-manager.sh
              dest: "{{ pywb_dir }}/wb-manager.sh"
        - name: "Collection tools"
          copy:
            src: "{{ item.src }}"
            dest: "{{ item.dest }}"
            mode: u+x
          loop:
            - src: collection-manager.sh
              dest: "{{ pywb_dir }}/collection-manager.sh"
            - src: cdxj-manager.sh
              dest: "{{ pywb_dir }}/cdxj-manager.sh"
        - name: "Logo"
          copy:
            src: logo.png
            dest: "{{ pywb_dir }}/logo.png"
